import getEnvVar from "~/utilities/get-env-var";

export default {
	BASE: getEnvVar("POTLUCK_QUEST_BASE_URL"),
	AUTH_CHECK_ACCOUNT_EXISTS: getEnvVar("POTLUCK_CHECK_ACCOUNT_EXISTS_API_URL"),
	AUTH_PLAN_FOOD: getEnvVar("POTLUCK_QUEST_AUTH_PLAN_FOOD_ROUTE"),
	AUTH_SETUP: getEnvVar("POTLUCK_QUEST_AUTH_SETUP_ROUTE"),
	COMMITMENT: getEnvVar("POTLUCK_COMMITMENT_API_URL"),
	EVENT: getEnvVar("POTLUCK_EVENT_API_URL"),
	RSVP: getEnvVar("POTLUCK_RSVP_API_URL"),
	SLOTS: getEnvVar("POTLUCK_SLOTS_API_URL"),
	TIMEZONE: getEnvVar("POTLUCK_TIMEZONE_API_ROUTE"),
};
